import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../project.dart';

/// `fkit theme` — generates the theme extensions widget_kit expects.
///
/// Without this file, widget_kit's buttons render in the brand red and orange
/// of the app the kit was extracted from: `AppButton` reads
/// `AppButtonThemeExtension`, whose defaults are hardcoded colours, and it
/// never consults `ColorScheme`. Registering both extensions is the fix, and
/// writing all ten button styles by hand is the reason nobody does it.
class ThemeCommand extends Command<int> {
  ThemeCommand(this._logger) {
    argParser
      ..addOption(
        'primary',
        abbr: 'p',
        help: 'Brand colour as a hex value, e.g. 104C65 or #104C65.',
      )
      ..addOption(
        'output',
        abbr: 'o',
        help: 'Where to write the file, relative to the project.',
        defaultsTo: 'lib/theme/kits_theme.dart',
      )
      ..addFlag(
        'force',
        abbr: 'f',
        negatable: false,
        help: 'Overwrite the file if it already exists.',
      );
  }

  final Logger _logger;

  @override
  String get name => 'theme';

  @override
  String get description =>
      'Generate the WidgetKitTheme + AppButtonThemeExtension boilerplate.';

  @override
  int run() {
    final project = Project.locate();

    final hex = argResults!.option('primary') ?? _promptForColour();
    final primary = _Rgb.parse(hex);

    final relative = argResults!.option('output')!;
    final file = File(p.join(project.root, relative));

    if (file.existsSync() && !argResults!.flag('force')) {
      if (!stdin.hasTerminal) {
        throw CliException(
          '${file.path} already exists; pass --force to overwrite.',
        );
      }
      if (!_logger.confirm('Overwrite ${file.path}?')) {
        _logger.info('Left the existing file alone.');
        return ExitCode.success.code;
      }
    }

    file
      ..createSync(recursive: true)
      ..writeAsStringSync(_render(primary));

    final import = relative.startsWith('lib/')
        ? "package:${project.name}/${relative.substring(4)}"
        : relative;

    _logger
      ..success('Created ${file.path}')
      ..info('')
      ..info('  Wire it up:')
      ..info(darkGray.wrap("    import '$import';")!)
      ..info('')
      ..info(darkGray.wrap('    MaterialApp(')!)
      ..info(darkGray.wrap('      theme: ThemeData.light().copyWith(')!)
      ..info(darkGray.wrap('        extensions: kitsThemeExtensions,')!)
      ..info(darkGray.wrap('      ),')!)
      ..info(darkGray.wrap('    );')!)
      ..info('');

    return ExitCode.success.code;
  }

  String _promptForColour() {
    if (!stdin.hasTerminal) {
      throw CliException(
        'No --primary given and no terminal to prompt from.\n'
        'Usage: fkit theme --primary 104C65',
      );
    }
    return _logger.prompt(
      'Brand colour (hex):',
      defaultValue: '104C65',
    );
  }

  /// The generated file. Every colour is emitted as a literal so the app does
  /// no colour maths at runtime and the values stay greppable.
  String _render(_Rgb primary) {
    final onPrimary = primary.isDark ? 'Color(0xFFFFFFFF)' : 'Color(0xFF1A1A1A)';
    final tonal = primary.mix(const _Rgb(255, 255, 255), 0.86);
    final onTonal = primary.darken(0.18);

    return '''
// Generated by `fkit theme`. Edit freely — it is not regenerated unless you
// re-run the command with --force.
//
// Both extensions are required for a consistent look:
//   • WidgetKitTheme          — inputs, dialogs, sheets, feedback, shimmer
//   • AppButtonThemeExtension — AppButton's ten styles
//
// AppButton reads only the second one. Drop it and every button falls back to
// widget_kit's built-in brand red.
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// The brand colour everything below is derived from.
const brandPrimary = ${primary.literal};
const brandOnPrimary = $onPrimary;
const brandTonal = ${tonal.literal};
const brandOnTonal = ${onTonal.literal};

/// Pass to `ThemeData.extensions`.
const kitsThemeExtensions = <ThemeExtension<dynamic>>[
  kitsWidgetTheme,
  kitsButtonTheme,
];

const kitsWidgetTheme = WidgetKitTheme(
  inputBorderRadius: 12,
  inputFocusedBorderColor: brandPrimary,
  buttonBorderRadius: 12,
  primaryButtonColor: brandPrimary,
  primaryButtonTextColor: brandOnPrimary,
  secondaryButtonColor: brandTonal,
  secondaryButtonTextColor: brandOnTonal,
  dialogBorderRadius: 20,
  sheetBorderRadius: 20,
  loadingColor: brandPrimary,
);

/// All ten styles must be supplied — the extension has no partial form.
const kitsButtonTheme = AppButtonThemeExtension(
  filled: AppButtonStyle(
    backgroundColor: brandPrimary,
    foregroundColor: brandOnPrimary,
    overlayColor: ${primary.literalWithAlpha(0x14)},
  ),
  filledTonal: AppButtonStyle(
    backgroundColor: brandTonal,
    foregroundColor: brandOnTonal,
    overlayColor: ${primary.literalWithAlpha(0x1A)},
  ),
  elevated: AppButtonStyle(
    backgroundColor: Color(0xFFFFFFFF),
    foregroundColor: brandPrimary,
    overlayColor: ${primary.literalWithAlpha(0x14)},
    elevation: 1,
  ),
  outlined: AppButtonStyle(
    backgroundColor: Color(0x00000000),
    foregroundColor: brandPrimary,
    overlayColor: ${primary.literalWithAlpha(0x0F)},
    borderColor: brandPrimary,
    borderSide: BorderSide(color: brandPrimary),
  ),
  text: AppButtonStyle(
    backgroundColor: Color(0x00000000),
    foregroundColor: brandPrimary,
    overlayColor: ${primary.literalWithAlpha(0x0F)},
  ),
  icon: AppButtonStyle(
    backgroundColor: Color(0x00000000),
    foregroundColor: Color(0xFF64748B),
    overlayColor: Color(0x1F64748B),
  ),
  iconFilled: AppButtonStyle(
    backgroundColor: brandPrimary,
    foregroundColor: brandOnPrimary,
    overlayColor: ${primary.literalWithAlpha(0x1F)},
  ),
  iconFilledTonal: AppButtonStyle(
    backgroundColor: brandTonal,
    foregroundColor: brandOnTonal,
    overlayColor: ${primary.literalWithAlpha(0x1F)},
  ),
  iconOutlined: AppButtonStyle(
    backgroundColor: Color(0x00000000),
    foregroundColor: brandPrimary,
    overlayColor: ${primary.literalWithAlpha(0x1F)},
    borderColor: Color(0xFFE2E8F0),
    borderSide: BorderSide(color: Color(0xFFE2E8F0)),
  ),
  fab: AppButtonStyle(
    backgroundColor: brandPrimary,
    foregroundColor: brandOnPrimary,
    overlayColor: ${primary.literalWithAlpha(0x14)},
    elevation: 3,
  ),
);
''';
  }
}

/// A plain 8-bit RGB colour, so the generator can derive tints without pulling
/// Flutter into a command-line tool.
class _Rgb {
  const _Rgb(this.r, this.g, this.b);

  factory _Rgb.parse(String input) {
    var hex = input.trim().replaceFirst('#', '').replaceFirst('0x', '');
    if (hex.length == 8) hex = hex.substring(2); // drop a leading alpha
    if (hex.length == 3) {
      hex = hex.split('').map((c) => '$c$c').join();
    }
    if (hex.length != 6 || !RegExp(r'^[0-9a-fA-F]{6}$').hasMatch(hex)) {
      throw CliException(
        'Could not read "$input" as a colour. Use a hex value like 104C65.',
      );
    }
    final value = int.parse(hex, radix: 16);
    return _Rgb((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF);
  }

  final int r;
  final int g;
  final int b;

  /// Perceived brightness (ITU-R BT.601), used to pick a readable foreground.
  bool get isDark => (r * 299 + g * 587 + b * 114) / 1000 < 150;

  _Rgb mix(_Rgb other, double amount) => _Rgb(
        (r + (other.r - r) * amount).round(),
        (g + (other.g - g) * amount).round(),
        (b + (other.b - b) * amount).round(),
      );

  _Rgb darken(double amount) => mix(const _Rgb(0, 0, 0), amount);

  String get _hex => [r, g, b]
      .map((c) => c.toRadixString(16).padLeft(2, '0').toUpperCase())
      .join();

  String get literal => 'Color(0xFF$_hex)';

  String literalWithAlpha(int alpha) =>
      'Color(0x${alpha.toRadixString(16).padLeft(2, '0').toUpperCase()}$_hex)';
}
