// GENERATED BY tool/sync_templates.dart — DO NOT EDIT BY HAND.
//
// Sources live in packages/docs/lib/{snippets,styles}/, where they
// are compiled against the real kits. Edit them there, then run
// `dart run tool/sync_templates.dart`.

/// A file `fkit` copies into a project.
///
/// Once written it belongs to the project: nothing tracks or
/// updates it afterwards.
class Template {
  const Template({
    required this.name,
    required this.description,
    required this.kits,
    required this.pub,
    required this.output,
    required this.body,
  });

  /// Kebab-case identifier passed on the command line.
  final String name;

  /// One line, shown by the matching `ls` command.
  final String description;

  /// Kits it imports; `create` checks they are installed.
  final List<String> kits;

  /// pub.dev packages it imports directly. A kit depending on one
  /// is not enough — your own code needs its own entry.
  final List<String> pub;

  /// Default destination, relative to the project root.
  final String output;

  /// The file contents.
  final String body;
}

/// Ready-made screens and widgets. `fkit snippet create`.
const kSnippets = <Template>[
  Template(
    name: 'app-shell',
    description: 'A MaterialApp wired for the kits — theme extensions, ProviderScope, toasts.',
    kits: ['widget_kit'],
    pub: ['hooks_riverpod'],
    output: 'lib/app.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:widget_kit/widget_kit.dart';

/// The root of an app using the kits.
///
/// Three things have to be in place, and each fails quietly if it isn't:
///
///  * **ProviderScope** — otp_kit and the other Riverpod-backed kits throw
///    without one.
///  * **ToastificationWrapper** — `UIHelper.showToast` needs it mounted above
///    the navigator. Without it toasts are silently dropped rather than
///    throwing, so the bug looks like "toasts don't work".
///  * **The theme extensions** — `AppButton` reads `AppButtonThemeExtension`
///    and nothing else. Leave it out and every button uses widget_kit's
///    built-in brand red. Run `fkit theme --primary <hex>` to generate a real
///    one, then swap it in for the defaults below.
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: ToastificationWrapper(
        child: MaterialApp(
          title: 'My App',
          debugShowCheckedModeBanner: false,
          theme: _theme(Brightness.light),
          darkTheme: _theme(Brightness.dark),
          home: const _Home(),
        ),
      ),
    );
  }

  ThemeData _theme(Brightness brightness) {
    final base = ThemeData(
      brightness: brightness,
      colorSchemeSeed: const Color(0xFF104C65),
      useMaterial3: true,
    );

    return base.copyWith(
      extensions: const <ThemeExtension<dynamic>>[
        // Replace both with the pair `fkit theme` generates.
        WidgetKitTheme(
          inputBorderRadius: 12,
          buttonBorderRadius: 12,
          dialogBorderRadius: 20,
          sheetBorderRadius: 20,
        ),
        AppButtonThemeExtension.defaults,
      ],
    );
  }
}

class _Home extends StatelessWidget {
  const _Home();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My App')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: AppButton(
            label: 'It works',
            widthMode: AppButtonWidthMode.hug,
            onPressed: () =>
                UIHelper.showSnackBar(context, message: 'Hello from widget_kit'),
          ),
        ),
      ),
    );
  }
}''',
  ),
  Template(
    name: 'async-button',
    description: 'A button that shows a spinner for the duration of an async call.',
    kits: ['widget_kit'],
    pub: [],
    output: 'lib/widgets/async_button.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// A button that runs [onPressed] and stays in its loading state until the
/// future completes.
///
/// AppButton ignores taps while `isLoading` is true, so there is no need to
/// null out the callback or guard against double submission yourself.
class AsyncButton extends StatefulWidget {
  const AsyncButton({
    super.key,
    required this.label,
    required this.onPressed,
    this.loadingLabel,
    this.style = AppButtonStyleType.filled,
    this.widthMode,
    this.icon,
  });

  final String label;

  /// Shown while the future is in flight. Falls back to [label].
  final String? loadingLabel;

  /// The work to run. Errors are rethrown after the loading state is cleared.
  final Future<void> Function() onPressed;

  final AppButtonStyleType style;
  final AppButtonWidthMode? widthMode;
  final Widget? icon;

  @override
  State<AsyncButton> createState() => _AsyncButtonState();
}

class _AsyncButtonState extends State<AsyncButton> {
  bool _busy = false;

  Future<void> _run() async {
    if (_busy) return;
    setState(() => _busy = true);
    try {
      await widget.onPressed();
    } finally {
      // The widget can be disposed mid-flight — navigating away during a save
      // is the common case — so never setState without checking.
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppButton(
      label: _busy ? (widget.loadingLabel ?? widget.label) : widget.label,
      icon: _busy ? null : widget.icon,
      style: widget.style,
      widthMode: widget.widthMode,
      isLoading: _busy,
      onPressed: _run,
    );
  }
}''',
  ),
  Template(
    name: 'confirm-dialog',
    description: 'A yes/no confirmation sheet for destructive actions.',
    kits: ['widget_kit'],
    pub: [],
    output: 'lib/widgets/confirm.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Asks the user to confirm a destructive action.
///
/// Returns true only if they explicitly confirmed — dismissing the dialog by
/// tapping outside or pressing back resolves to false, never null, so callers
/// can treat the result as a plain bool.
Future<bool> confirmAction(
  BuildContext context, {
  required String title,
  required String message,
  String confirmText = 'Delete',
  String cancelText = 'Cancel',
  Color? dangerColor,
}) async {
  final result = await showDialog<bool>(
    context: context,
    builder: (dialogContext) => AppWarningDialog(
      title: title,
      message: message,
      buttonText: confirmText,
      cancelText: cancelText,
      dangerColor: dangerColor,
      onPressed: () => Navigator.of(dialogContext).pop(true),
    ),
  );

  return result ?? false;
}

/// Example call site — delete the file after copying the function above.
class DeleteAccountTile extends StatelessWidget {
  const DeleteAccountTile({super.key, required this.onConfirmed});

  final Future<void> Function() onConfirmed;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      leading: const Icon(Icons.delete_outline_rounded),
      title: const Text('Delete account'),
      onTap: () async {
        final confirmed = await confirmAction(
          context,
          title: 'Delete account?',
          message: 'This permanently removes your data. It cannot be undone.',
        );
        if (!confirmed) return;

        await onConfirmed();
        // `context` may be gone after the await, so guard before using it.
        if (context.mounted) {
          UIHelper.showSnackBar(context, message: 'Account deleted');
        }
      },
    );
  }
}''',
  ),
  Template(
    name: 'otp-screen',
    description: 'A full OTP verification screen with resend cooldown.',
    kits: ['otp_kit'],
    pub: ['hooks_riverpod'],
    output: 'lib/features/auth/otp_screen.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:otp_kit/otp_kit.dart';

/// A complete verification screen: the code field, a resend button with its
/// cooldown, and a verify action.
///
/// otp_kit keeps its state in Riverpod, so this must sit under a ProviderScope.
class OtpScreen extends ConsumerStatefulWidget {
  const OtpScreen({
    super.key,
    required this.phoneNumber,
    required this.onVerify,
    required this.onResend,
  });

  /// Shown in the subtitle so the user can check they typed it correctly.
  final String phoneNumber;

  /// Called with the entered code. Return an error message to display, or null
  /// when verification succeeded.
  final Future<String?> Function(String code) onVerify;

  /// Ask your backend to send a new code.
  final Future<void> Function() onResend;

  @override
  ConsumerState<OtpScreen> createState() => _OtpScreenState();
}

class _OtpScreenState extends ConsumerState<OtpScreen> {
  // Two separate configs: the field's look and length, and the resend
  // cooldown. `namespace` is the key the cooldown is persisted under — give
  // each flow its own so a signup countdown doesn't block a login one.
  late final OTPConfig _config = OTPTheme.custom(
    context: context,
    length: 6,
  );

  static const _cooldown = ResendCooldownConfig(namespace: 'verify-phone');

  bool _verifying = false;

  OTPController get _controller =>
      ref.read(otpControllerProvider(_config).notifier);

  Future<void> _verify(String code) async {
    if (_verifying) return;
    setState(() => _verifying = true);

    final error = await widget.onVerify(code);

    if (!mounted) return;
    setState(() => _verifying = false);

    // Push the failure back into the field so it shows its error styling and
    // the user can correct it in place.
    if (error != null) _controller.setError(error);
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final state = ref.watch(otpControllerProvider(_config));

    return Scaffold(
      appBar: AppBar(title: const Text('Verify your number')),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 12),
              Text('Enter the code', style: theme.textTheme.headlineSmall),
              const SizedBox(height: 8),
              Text(
                'We sent a 6-digit code to ${widget.phoneNumber}.',
                style: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
              const SizedBox(height: 32),
              OTPTextField(
                config: _config,
                onCompleted: _verify,
              ),
              const SizedBox(height: 24),
              OTPResendButton(
                config: _cooldown,
                labels: ResendButtonLabels(
                  resend: 'Resend code',
                  shortCooldown: (t) => 'Resend in $t',
                  longCooldown: (t) => 'Try again in $t',
                ),
                onResend: () async {
                  await widget.onResend();
                  // Starts the next cooldown; without this the button stays
                  // available and users can spam your SMS provider.
                  ref
                      .read(resendCooldownProvider(_cooldown).notifier)
                      .recordResend();
                },
                buttonBuilder: (context, {required label, required onPressed}) {
                  return TextButton(onPressed: onPressed, child: Text(label));
                },
              ),
              const Spacer(),
              FilledButton(
                onPressed: state.isComplete && !_verifying
                    ? () => _verify(state.value)
                    : null,
                child: _verifying
                    ? const SizedBox(
                        height: 18,
                        width: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Verify'),
              ),
              const SizedBox(height: 12),
            ],
          ),
        ),
      ),
    );
  }
}''',
  ),
];

/// Per-widget theming boilerplate. `fkit style create`.
const kStyles = <Template>[
  Template(
    name: 'app-button',
    description: 'All ten AppButton styles, written out so any of them can be edited.',
    kits: ['widget_kit'],
    pub: [],
    output: 'lib/theme/styles/app_button_style.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create app-button`.
///
/// Every one of AppButton's ten styles, spelled out rather than inherited, so
/// you can change one without reconstructing the other nine. Edit the body and
/// pass the result to `ThemeData.extensions`.
///
/// `AppButton` reads **only** this extension. `WidgetKitTheme`'s
/// `primaryButtonColor` / `buttonBorderRadius` fields have no effect on it.
///
/// ```dart
/// MaterialApp(
///   theme: ThemeData.light().copyWith(
///     extensions: [
///       appButtonTheme(
///         primary: const Color(0xFF104C65),
///         onPrimary: Colors.white,
///         tonal: const Color(0xFFDEE6E9),
///         onTonal: const Color(0xFF0D3E53),
///       ),
///     ],
///   ),
/// );
/// ```
AppButtonThemeExtension appButtonTheme({
  required Color primary,
  required Color onPrimary,
  required Color tonal,
  required Color onTonal,

  /// Surface behind the elevated style. Pass your dark surface in a dark theme
  /// — the kit's own default is an opaque white that does not adapt.
  Color surface = const Color(0xFFFFFFFF),

  /// Standard and outlined icon buttons are deliberately quiet.
  Color iconForeground = const Color(0xFF64748B),
  Color iconBorder = const Color(0xFFE2E8F0),
}) {
  // Material's state-layer opacities: 8% hover/press on filled surfaces,
  // 6% on the transparent styles, 12% on icon buttons.
  final overlay = primary.withValues(alpha: 0.08);
  final overlaySoft = primary.withValues(alpha: 0.06);
  final overlayStrong = primary.withValues(alpha: 0.12);

  return AppButtonThemeExtension(
    filled: AppButtonStyle(
      backgroundColor: primary,
      foregroundColor: onPrimary,
      overlayColor: overlay,
    ),
    filledTonal: AppButtonStyle(
      backgroundColor: tonal,
      foregroundColor: onTonal,
      overlayColor: overlay,
    ),
    elevated: AppButtonStyle(
      backgroundColor: surface,
      foregroundColor: primary,
      overlayColor: overlay,
      elevation: 1,
    ),
    outlined: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: primary,
      overlayColor: overlaySoft,
      borderColor: primary,
      borderSide: BorderSide(color: primary),
    ),
    text: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: primary,
      overlayColor: overlaySoft,
    ),
    icon: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: iconForeground,
      overlayColor: iconForeground.withValues(alpha: 0.12),
    ),
    iconFilled: AppButtonStyle(
      backgroundColor: primary,
      foregroundColor: onPrimary,
      overlayColor: overlayStrong,
    ),
    iconFilledTonal: AppButtonStyle(
      backgroundColor: tonal,
      foregroundColor: onTonal,
      overlayColor: overlayStrong,
    ),
    iconOutlined: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: iconForeground,
      overlayColor: iconForeground.withValues(alpha: 0.12),
      borderColor: iconBorder,
      borderSide: BorderSide(color: iconBorder),
    ),
    fab: AppButtonStyle(
      backgroundColor: primary,
      foregroundColor: onPrimary,
      overlayColor: overlay,
      elevation: 3,
    ),
  );
}''',
  ),
  Template(
    name: 'feedback',
    description: 'Empty and error states, loading colour, shimmer, media placeholders.',
    kits: ['widget_kit'],
    pub: [],
    output: 'lib/theme/styles/feedback_style.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create feedback`.
///
/// The states a screen shows when it has nothing to show: empty and error
/// placeholders, the loading indicator, shimmer, and the media placeholder.
/// Chain it with the other `WidgetKitTheme` styles.
///
/// ```dart
/// extensions: [
///   feedbackStyle(WidgetKitTheme.fallback, primary: brand),
///   appButtonTheme(primary: brand, /* … */),
/// ]
/// ```
WidgetKitTheme feedbackStyle(
  WidgetKitTheme base, {
  required Color primary,

  /// Shimmer reads as a sweep across a resting block, so the two colours must
  /// differ noticeably or the animation is invisible.
  Color shimmerBase = const Color(0xFFE2E8F0),
  Color shimmerHighlight = const Color(0xFFF1F5F9),
  Color placeholder = const Color(0xFFE2E8F0),
  Color? emptyIcon,
  Color? errorIcon,
}) => base.copyWith(
  loadingColor: primary,
  emptyStateIconColor: emptyIcon,
  errorStateIconColor: errorIcon,
  shimmerBaseColor: shimmerBase,
  shimmerHighlightColor: shimmerHighlight,
  mediaPlaceholderColor: placeholder,
  mediaErrorIconColor: errorIcon,
);''',
  ),
  Template(
    name: 'input',
    description: 'AppTextFormField\'s borders, colours and text sizes.',
    kits: ['widget_kit'],
    pub: [],
    output: 'lib/theme/styles/input_style.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create input`.
///
/// Unlike AppButton, the inputs, dialogs, feedback states and shimmer all read
/// the **same** `WidgetKitTheme` extension — there can only be one of it on a
/// `ThemeData`. So each generated style takes a base and returns it modified,
/// and you chain the ones you want:
///
/// ```dart
/// extensions: [
///   inputStyle(dialogStyle(WidgetKitTheme.fallback), primary: brand),
///   appButtonTheme(primary: brand, /* … */),
/// ]
/// ```
///
/// The values below are widget_kit's own defaults. Change what you need and
/// leave the rest.
WidgetKitTheme inputStyle(
  WidgetKitTheme base, {
  required Color primary,
  Color? border,
  Color? background,
  Color? text,
  Color? hint,
  Color? error,
}) => base.copyWith(
  // WidgetKitTokens.radiusSm / borderThin / borderThick
  inputBorderRadius: 8,
  inputBorderWidth: 1,
  inputFocusedBorderWidth: 2,

  inputBorderColor: border,
  inputFocusedBorderColor: primary,
  inputBackgroundColor: background,
  inputTextColor: text,
  inputHintColor: hint,
  inputErrorColor: error,

  // WidgetKitTokens.fontMd / fontSm
  inputFontSize: 14,
  inputHintFontSize: 12,
);''',
  ),
  Template(
    name: 'surface',
    description: 'Dialog and bottom-sheet corner radii and backgrounds.',
    kits: ['widget_kit'],
    pub: [],
    output: 'lib/theme/styles/surface_style.dart',
    body: r'''
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create surface`.
///
/// Dialogs and bottom sheets. Chain it with the other `WidgetKitTheme` styles —
/// they all write into the same extension:
///
/// ```dart
/// extensions: [
///   surfaceStyle(inputStyle(WidgetKitTheme.fallback, primary: brand)),
///   appButtonTheme(primary: brand, /* … */),
/// ]
/// ```
WidgetKitTheme surfaceStyle(
  WidgetKitTheme base, {
  Color? dialogBackground,
}) => base.copyWith(
  // WidgetKitTokens.radiusLg
  dialogBorderRadius: 16,
  sheetBorderRadius: 16,
  dialogBackgroundColor: dialogBackground,
);''',
  ),
];
