// Regenerates lib/src/catalog.g.dart from the monorepo.
//
// The CLI runs inside someone else's project, so it cannot read the monorepo at
// runtime — the kit list has to be baked in. This keeps that baked-in copy
// honest: run it after adding a kit or tagging a release.
//
//   dart run tool/sync_catalog.dart
//
// Facts come from two places, both authoritative:
//   • each sibling package's pubspec.yaml → name, version, description
//   • the newest `v*` git tag             → the ref `fkit add` writes
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Directories in the monorepo that are not consumable kits.
const _excluded = {'docs', 'tool', 'flutter_kits_cli'};

void main() {
  final cliRoot = Directory.current.path;
  final monorepo = p.dirname(cliRoot);

  final kits = _readKits(monorepo);
  if (kits.isEmpty) {
    stderr.writeln(
      'No kits found under $monorepo. Run this from packages/flutter_kits_cli.',
    );
    exit(1);
  }

  final ref = _latestTag(monorepo);
  if (ref == null) {
    stderr.writeln('No v* git tag found — cannot determine the ref to pin.');
    exit(1);
  }

  final out = File(p.join(cliRoot, 'lib', 'src', 'catalog.g.dart'));
  out.writeAsStringSync(_render(kits, ref));

  stdout.writeln('Wrote ${kits.length} kits at ref $ref → ${out.path}');
}

List<_Entry> _readKits(String monorepo) {
  final kits = <_Entry>[];

  for (final entity in Directory(monorepo).listSync().whereType<Directory>()) {
    final name = p.basename(entity.path);
    if (name.startsWith('.') || _excluded.contains(name)) continue;

    final pubspec = File(p.join(entity.path, 'pubspec.yaml'));
    if (!pubspec.existsSync()) continue;

    final yaml = loadYaml(pubspec.readAsStringSync()) as YamlMap;
    final packageName = yaml['name'] as String?;
    if (packageName == null) continue;

    // A package whose directory and name disagree can't be installed by
    // `path:` + package name, so refuse to publish a catalog entry that lies.
    if (packageName != name) {
      stderr.writeln(
        'Skipping $name: pubspec declares name "$packageName". '
        'The directory and package name must match.',
      );
      continue;
    }

    kits.add(_Entry(
      name: packageName,
      version: (yaml['version'] as Object?)?.toString() ?? '0.0.0',
      description: _oneLine(yaml['description'] as String? ?? ''),
    ));
  }

  kits.sort((a, b) => a.name.compareTo(b.name));
  return kits;
}

/// Collapses a folded/multi-line pubspec description to a single sentence-ish
/// line, so it fits a terminal row.
String _oneLine(String raw) {
  final flat = raw.replaceAll(RegExp(r'\s+'), ' ').trim();
  final stop = flat.indexOf(RegExp(r'[.—] '));
  final trimmed = (stop > 40 ? flat.substring(0, stop) : flat).trim();
  return trimmed.length > 150 ? '${trimmed.substring(0, 147)}…' : trimmed;
}

/// The newest `v*` tag by version order — what a consumer should pin to.
String? _latestTag(String monorepo) {
  final result = Process.runSync(
    'git',
    ['tag', '--list', 'v*', '--sort=-v:refname'],
    workingDirectory: monorepo,
  );
  if (result.exitCode != 0) return null;

  final tags = (result.stdout as String)
      .split('\n')
      .map((t) => t.trim())
      .where((t) => t.isNotEmpty)
      // Skip descriptive tags like v1.1.7-decouple-…; pin to plain releases.
      .where((t) => RegExp(r'^v\d+\.\d+\.\d+$').hasMatch(t));

  return tags.isEmpty ? null : tags.first;
}

String _render(List<_Entry> kits, String ref) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/sync_catalog.dart — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Run `dart run tool/sync_catalog.dart` from packages/flutter_kits_cli')
    ..writeln('// after adding a kit or tagging a release.')
    ..writeln()
    ..writeln("import 'kit.dart';")
    ..writeln()
    ..writeln('/// The monorepo the kits are fetched from.')
    ..writeln(
      "const kRepoUrl = 'https://github.com/loqmanali/flutter_kits.git';",
    )
    ..writeln()
    ..writeln('/// The newest monorepo release tag.')
    ..writeln('///')
    ..writeln('/// Kits are pinned to this, not to their own package versions:')
    ..writeln('/// widget_kit 1.2.0 ships *inside* this tag, and no `v1.2.0`')
    ..writeln('/// tag exists to pin to.')
    ..writeln("const kDefaultRef = '$ref';")
    ..writeln()
    ..writeln('/// Every installable kit, sorted by name.')
    ..writeln('const kCatalog = <Kit>[');

  for (final kit in kits) {
    buffer
      ..writeln('  Kit(')
      ..writeln("    name: '${kit.name}',")
      ..writeln("    version: '${kit.version}',")
      ..writeln("    description: '${_escape(kit.description)}',")
      ..writeln('  ),');
  }

  buffer.writeln('];');
  return buffer.toString();
}

String _escape(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

class _Entry {
  const _Entry({
    required this.name,
    required this.version,
    required this.description,
  });

  final String name;
  final String version;
  final String description;
}
