// Regenerates lib/src/templates.g.dart from the docs app's template sources.
//
//   dart run tool/sync_templates.dart
//
// Two kinds of file get copied into a user's project, and both are kept as real
// Dart in ../docs/lib/ rather than as strings here — that package depends on
// the kits, so `flutter analyze` proves each one still compiles against the
// current API. A CLI cannot do that for code it stores as text.
//
//   snippets/  ready-made screens and widgets   → fkit snippet create
//   styles/    per-widget theming boilerplate   → fkit style create
//
// Each source carries its metadata in a header comment, stripped before the
// body is emitted:
//
//   // template: app-button
//   // description: All ten AppButton styles, written out.
//   // kits: widget_kit
//   // pub: hooks_riverpod          (optional)
//   // output: lib/theme/styles/app_button_style.dart
import 'dart:io';

import 'package:path/path.dart' as p;

/// Source directory → the generated constant it populates.
const _sets = {'snippets': 'kSnippets', 'styles': 'kStyles'};

void main() {
  final cliRoot = Directory.current.path;
  final docsLib = p.join(p.dirname(cliRoot), 'docs', 'lib');

  final collected = <String, List<_Template>>{};

  for (final entry in _sets.entries) {
    final dir = Directory(p.join(docsLib, entry.key));
    if (!dir.existsSync()) {
      stderr.writeln('No template sources at ${dir.path}.');
      exit(1);
    }

    final templates = dir
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))
        .map(_parse)
        .whereType<_Template>()
        .toList()
      ..sort((a, b) => a.name.compareTo(b.name));

    if (templates.isEmpty) {
      stderr.writeln('Found no "// template:" headers in ${dir.path}.');
      exit(1);
    }
    collected[entry.value] = templates;
  }

  // A name used by both sets would be ambiguous to a reader even though the
  // two commands are separate.
  final seen = <String, String>{};
  for (final entry in collected.entries) {
    for (final t in entry.value) {
      final clash = seen[t.name];
      if (clash != null) {
        stderr.writeln('Duplicate template name "${t.name}" in $clash and ${entry.key}.');
        exit(1);
      }
      seen[t.name] = entry.key;
    }
  }

  File(p.join(cliRoot, 'lib', 'src', 'templates.g.dart'))
      .writeAsStringSync(_render(collected));

  for (final entry in collected.entries) {
    stdout.writeln('${entry.key}: ${entry.value.length}');
    for (final t in entry.value) {
      stdout.writeln('  ${t.name} → ${t.output}');
    }
  }
}

_Template? _parse(File file) {
  final lines = file.readAsLinesSync();
  final meta = <String, String>{};

  var bodyStart = 0;
  for (var i = 0; i < lines.length; i++) {
    final match = RegExp(r'^// (\w+):\s*(.*)$').firstMatch(lines[i]);
    if (match != null) {
      meta[match.group(1)!] = match.group(2)!.trim();
      bodyStart = i + 1;
      continue;
    }
    // Allow prose comment lines between the header and the code, but stop at
    // the first line that is not a comment at all.
    if (lines[i].startsWith('//')) {
      bodyStart = i + 1;
      continue;
    }
    break;
  }

  final name = meta['template'];
  if (name == null) {
    stderr.writeln('Skipping ${p.basename(file.path)}: no "// template:" header.');
    return null;
  }

  for (final required in ['description', 'kits', 'output']) {
    if (!meta.containsKey(required)) {
      stderr.writeln('${p.basename(file.path)} is missing "// $required:".');
      exit(1);
    }
  }

  List<String> csv(String? value) => value == null || value.isEmpty
      ? const []
      : value.split(',').map((v) => v.trim()).where((v) => v.isNotEmpty).toList();

  final body = lines.sublist(bodyStart).join('\n').trimLeft();

  // The body is emitted inside a raw triple-quoted string, so a triple-quote in
  // the source would end it early and produce a file that does not parse.
  if (body.contains("'''")) {
    stderr.writeln(
      '${p.basename(file.path)} contains a triple-quote, which cannot be '
      'embedded. Rewrite it or extend the generator.',
    );
    exit(1);
  }

  return _Template(
    name: name,
    description: meta['description']!,
    kits: csv(meta['kits']),
    pub: csv(meta['pub']),
    output: meta['output']!,
    body: body,
  );
}

String _render(Map<String, List<_Template>> sets) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/sync_templates.dart — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Sources live in packages/docs/lib/{snippets,styles}/, where they')
    ..writeln('// are compiled against the real kits. Edit them there, then run')
    ..writeln('// `dart run tool/sync_templates.dart`.')
    ..writeln()
    ..writeln('/// A file `fkit` copies into a project.')
    ..writeln('///')
    ..writeln('/// Once written it belongs to the project: nothing tracks or')
    ..writeln('/// updates it afterwards.')
    ..writeln('class Template {')
    ..writeln('  const Template({')
    ..writeln('    required this.name,')
    ..writeln('    required this.description,')
    ..writeln('    required this.kits,')
    ..writeln('    required this.pub,')
    ..writeln('    required this.output,')
    ..writeln('    required this.body,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  /// Kebab-case identifier passed on the command line.')
    ..writeln('  final String name;')
    ..writeln()
    ..writeln('  /// One line, shown by the matching `ls` command.')
    ..writeln('  final String description;')
    ..writeln()
    ..writeln('  /// Kits it imports; `create` checks they are installed.')
    ..writeln('  final List<String> kits;')
    ..writeln()
    ..writeln('  /// pub.dev packages it imports directly. A kit depending on one')
    ..writeln('  /// is not enough — your own code needs its own entry.')
    ..writeln('  final List<String> pub;')
    ..writeln()
    ..writeln('  /// Default destination, relative to the project root.')
    ..writeln('  final String output;')
    ..writeln()
    ..writeln('  /// The file contents.')
    ..writeln('  final String body;')
    ..writeln('}');

  const docs = {
    'kSnippets': 'Ready-made screens and widgets. `fkit snippet create`.',
    'kStyles': 'Per-widget theming boilerplate. `fkit style create`.',
  };

  for (final entry in sets.entries) {
    buffer
      ..writeln()
      ..writeln('/// ${docs[entry.key]}')
      ..writeln('const ${entry.key} = <Template>[');

    for (final t in entry.value) {
      buffer
        ..writeln('  Template(')
        ..writeln("    name: '${t.name}',")
        ..writeln("    description: '${t.description.replaceAll("'", r"\'")}',")
        ..writeln('    kits: [${t.kits.map((k) => "'$k'").join(', ')}],')
        ..writeln('    pub: [${t.pub.map((k) => "'$k'").join(', ')}],')
        ..writeln("    output: '${t.output}',")
        ..writeln("    body: r'''")
        ..write(t.body)
        ..writeln("''',")
        ..writeln('  ),');
    }
    buffer.writeln('];');
  }

  return buffer.toString();
}

class _Template {
  const _Template({
    required this.name,
    required this.description,
    required this.kits,
    required this.pub,
    required this.output,
    required this.body,
  });

  final String name;
  final String description;
  final List<String> kits;
  final List<String> pub;
  final String output;
  final String body;
}
