// template: app-button
// description: All ten AppButton styles, written out so any of them can be edited.
// kits: widget_kit
// output: lib/theme/styles/app_button_style.dart
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create app-button`.
///
/// Every one of AppButton's ten styles, spelled out rather than inherited, so
/// you can change one without reconstructing the other nine. Edit the body and
/// pass the result to `ThemeData.extensions`.
///
/// `AppButton` reads **only** this extension. `WidgetKitTheme`'s
/// `primaryButtonColor` / `buttonBorderRadius` fields have no effect on it.
///
/// ```dart
/// MaterialApp(
///   theme: ThemeData.light().copyWith(
///     extensions: [
///       appButtonTheme(
///         primary: const Color(0xFF104C65),
///         onPrimary: Colors.white,
///         tonal: const Color(0xFFDEE6E9),
///         onTonal: const Color(0xFF0D3E53),
///       ),
///     ],
///   ),
/// );
/// ```
AppButtonThemeExtension appButtonTheme({
  required Color primary,
  required Color onPrimary,
  required Color tonal,
  required Color onTonal,

  /// Surface behind the elevated style. Pass your dark surface in a dark theme
  /// — the kit's own default is an opaque white that does not adapt.
  Color surface = const Color(0xFFFFFFFF),

  /// Standard and outlined icon buttons are deliberately quiet.
  Color iconForeground = const Color(0xFF64748B),
  Color iconBorder = const Color(0xFFE2E8F0),
}) {
  // Material's state-layer opacities: 8% hover/press on filled surfaces,
  // 6% on the transparent styles, 12% on icon buttons.
  final overlay = primary.withValues(alpha: 0.08);
  final overlaySoft = primary.withValues(alpha: 0.06);
  final overlayStrong = primary.withValues(alpha: 0.12);

  return AppButtonThemeExtension(
    filled: AppButtonStyle(
      backgroundColor: primary,
      foregroundColor: onPrimary,
      overlayColor: overlay,
    ),
    filledTonal: AppButtonStyle(
      backgroundColor: tonal,
      foregroundColor: onTonal,
      overlayColor: overlay,
    ),
    elevated: AppButtonStyle(
      backgroundColor: surface,
      foregroundColor: primary,
      overlayColor: overlay,
      elevation: 1,
    ),
    outlined: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: primary,
      overlayColor: overlaySoft,
      borderColor: primary,
      borderSide: BorderSide(color: primary),
    ),
    text: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: primary,
      overlayColor: overlaySoft,
    ),
    icon: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: iconForeground,
      overlayColor: iconForeground.withValues(alpha: 0.12),
    ),
    iconFilled: AppButtonStyle(
      backgroundColor: primary,
      foregroundColor: onPrimary,
      overlayColor: overlayStrong,
    ),
    iconFilledTonal: AppButtonStyle(
      backgroundColor: tonal,
      foregroundColor: onTonal,
      overlayColor: overlayStrong,
    ),
    iconOutlined: AppButtonStyle(
      backgroundColor: const Color(0x00000000),
      foregroundColor: iconForeground,
      overlayColor: iconForeground.withValues(alpha: 0.12),
      borderColor: iconBorder,
      borderSide: BorderSide(color: iconBorder),
    ),
    fab: AppButtonStyle(
      backgroundColor: primary,
      foregroundColor: onPrimary,
      overlayColor: overlay,
      elevation: 3,
    ),
  );
}
