// template: feedback
// description: Empty and error states, loading colour, shimmer, media placeholders.
// kits: widget_kit
// output: lib/theme/styles/feedback_style.dart
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create feedback`.
///
/// The states a screen shows when it has nothing to show: empty and error
/// placeholders, the loading indicator, shimmer, and the media placeholder.
/// Chain it with the other `WidgetKitTheme` styles.
///
/// ```dart
/// extensions: [
///   feedbackStyle(WidgetKitTheme.fallback, primary: brand),
///   appButtonTheme(primary: brand, /* … */),
/// ]
/// ```
WidgetKitTheme feedbackStyle(
  WidgetKitTheme base, {
  required Color primary,

  /// Shimmer reads as a sweep across a resting block, so the two colours must
  /// differ noticeably or the animation is invisible.
  Color shimmerBase = const Color(0xFFE2E8F0),
  Color shimmerHighlight = const Color(0xFFF1F5F9),
  Color placeholder = const Color(0xFFE2E8F0),
  Color? emptyIcon,
  Color? errorIcon,
}) => base.copyWith(
  loadingColor: primary,
  emptyStateIconColor: emptyIcon,
  errorStateIconColor: errorIcon,
  shimmerBaseColor: shimmerBase,
  shimmerHighlightColor: shimmerHighlight,
  mediaPlaceholderColor: placeholder,
  mediaErrorIconColor: errorIcon,
);
