// template: input
// description: AppTextFormField's borders, colours and text sizes.
// kits: widget_kit
// output: lib/theme/styles/input_style.dart
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create input`.
///
/// Unlike AppButton, the inputs, dialogs, feedback states and shimmer all read
/// the **same** `WidgetKitTheme` extension — there can only be one of it on a
/// `ThemeData`. So each generated style takes a base and returns it modified,
/// and you chain the ones you want:
///
/// ```dart
/// extensions: [
///   inputStyle(dialogStyle(WidgetKitTheme.fallback), primary: brand),
///   appButtonTheme(primary: brand, /* … */),
/// ]
/// ```
///
/// The values below are widget_kit's own defaults. Change what you need and
/// leave the rest.
WidgetKitTheme inputStyle(
  WidgetKitTheme base, {
  required Color primary,
  Color? border,
  Color? background,
  Color? text,
  Color? hint,
  Color? error,
}) => base.copyWith(
  // WidgetKitTokens.radiusSm / borderThin / borderThick
  inputBorderRadius: 8,
  inputBorderWidth: 1,
  inputFocusedBorderWidth: 2,

  inputBorderColor: border,
  inputFocusedBorderColor: primary,
  inputBackgroundColor: background,
  inputTextColor: text,
  inputHintColor: hint,
  inputErrorColor: error,

  // WidgetKitTokens.fontMd / fontSm
  inputFontSize: 14,
  inputHintFontSize: 12,
);
