// template: surface
// description: Dialog and bottom-sheet corner radii and backgrounds.
// kits: widget_kit
// output: lib/theme/styles/surface_style.dart
import 'package:flutter/material.dart';
import 'package:widget_kit/widget_kit.dart';

/// Generated by `fkit style create surface`.
///
/// Dialogs and bottom sheets. Chain it with the other `WidgetKitTheme` styles —
/// they all write into the same extension:
///
/// ```dart
/// extensions: [
///   surfaceStyle(inputStyle(WidgetKitTheme.fallback, primary: brand)),
///   appButtonTheme(primary: brand, /* … */),
/// ]
/// ```
WidgetKitTheme surfaceStyle(
  WidgetKitTheme base, {
  Color? dialogBackground,
}) => base.copyWith(
  // WidgetKitTokens.radiusLg
  dialogBorderRadius: 16,
  sheetBorderRadius: 16,
  dialogBackgroundColor: dialogBackground,
);
