include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    use_build_context_synchronously: error
    avoid_print: error
    implementation_imports: error
  exclude:
    - "**/*.g.dart"
    - "**/*.drift.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    require_trailing_commas: true
    avoid_print: true
    always_use_package_imports: true
    prefer_final_locals: true
    unawaited_futures: true
